version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: npm install
            - run: npm run nx affected --target=lint --base=origin/master~1 --parallel
            - run: npm run nx affected --target=test --base=origin/master~1 --parallel
            - run: npm run ng build --project rxjs-state -prod
            - run: npm run ng build --project ngx-rx-state -prod
workflows:
    build-and-test:
      jobs:
        - build-and-test
