version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: yarn install --frozen-lockfile --non-interactive
            - run: yarn affected:lint --all
            - run: yarn affected:test --all
            - run: yarn affected:build --all --with-deps
workflows:
    build-and-test:
      jobs:
        - build-and-test
