version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: npm install --frozen-lockfile --non-interactive
            - run: npm run affected:lint
            - run: npm run nx test state
            - run: npm run nx build state --  --with-deps
workflows:
    build-and-test:
      jobs:
        - build-and-test
