version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: npm install
            - run:
                name: 'Test with code-coverage'
                command: yarn nx affected --target=test --code-coverage --base=origin/master~1 --parallel
            - run:
                name: 'Test with code-coverage'
                comand: yarn nx affected --target=build --base=origin/master~1 --only-failed
workflows:
    build-and-test:
      jobs:
        - build-and-test
