version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: npm install
            - run: npm run affected:lint --  --parallel
            - run: npm run affected:test --  --parallel
            - run: npm run affected:build --  --with-deps
workflows:
    build-and-test:
      jobs:
        - build-and-test
