version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: yarn install
            - run: yarn nx run --target=lint --all
            - run: yarn nx run --target=test --all
            - run: yarn nx run --target=build --all --with-deps
workflows:
    build-and-test:
      jobs:
        - build-and-test
